//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbsentLog
    {
        public short IdAbsentType { get; set; }
        public int Id { get; set; }
        public string Reason { get; set; }
    
        public virtual AbsentType AbsentType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
