//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AbsentLogs = new HashSet<AbsentLog>();
            this.SalaryLogs = new HashSet<SalaryLog>();
            this.WorkLogs = new HashSet<WorkLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Dob { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public short IdPosition { get; set; }
        public short IdEduType { get; set; }
        public short IdState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbsentLog> AbsentLogs { get; set; }
        public virtual EducationType EducationType { get; set; }
        public virtual PositionType PositionType { get; set; }
        public virtual EmployeeState EmployeeState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryLog> SalaryLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkLog> WorkLogs { get; set; }
    }
}
