//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PositionType()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public short IdPosition { get; set; }
        public string NamePosition { get; set; }
        public double BaseSalary { get; set; }
        public short IdWorkType { get; set; }
        public Nullable<short> IdEmployeeTypes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual WorkType WorkType { get; set; }
    }
}
